---
apiVersion: v1
kind: Service
metadata:
  name: order-ms
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: order-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080